### ISSUE TITLE
Locked taskbar obscures PerfMonBar

### ISSUE THREAD

**Issue by campbellkerr** [XhmikosR/perfmonbar#17]
This stumped me for a while... Maybe more of a heads up.

After installing and enabling PerfMonBar, all I could see was this:

![image](https://user-images.githubusercontent.com/38451588/91027912-0edecf80-e640-11ea-94b8-3ed6e22c68e4.png)

Found I had to unlock the taskbar, drag and resize it, then I could see PerfMonBar and could re-lock the taskbar.

![image](https://user-images.githubusercontent.com/38451588/91037091-c9c09a80-e64b-11ea-8de8-a6e089a3df16.png)

Thanks

**Comment by campbellkerr** [comment]
BTW after RDP'ing back to the same Win10 box as above, it looks like it's pushed the taskbar which has partially hidden the perfmonbar again. Not sure if there's anything that can be done as it might be Windows resizing in whichever way it feels like.

**Comment by Volkanite** [comment]
And this is exactly why I made [this](https://github.com/XhmikosR/perfmonbar/pull/13) pull request over a month ago. The problem is that the deskband has a minimum size of 10 by default, and this isn't changeable, it's hardcoded into the program. Having a minimum size of 10 means that the deskband can shrink to that size when other programs start eating up the taskbar space. For me, a minimum size of 100 is much more reasonable. The PR I made allows you to set both horizontal and vertical minimum size of the deskband. I'm not sure but the owner of this repo seems to not pay it much attention. If it goes more than 3 months then I guess I'll just focus on my fork of repository and keep developing it. [Here](https://mega.nz/file/IIkBma4I#n0dX9iociFp9KCYTCUYpnas30ZwDSuu6At1XqitlJjo) is a compiled DLL if you aren't willing to spend the time to build my fork of the project. To utilize my PR, overwrite the existing PerfmonBar.dll, then set _minSizeX_ and _minSizeY_ under a new node called _settings_ in config.xml. For our problem, just focus on minSizeX, which is the horizontal minimum size:

```
<perfbar>
    <settings minSizeX="116" minSizeY="10">
    </settings>
</perfbar>
```
